"""Populate the shop with mock stock so the UI can be tested immediately.

    python manage.py seed_data                   # catalogue only
    python manage.py seed_data --images          # also draw product photos
    python manage.py seed_data --flush --images  # wipe first, then rebuild

Safe to re-run: rows are matched on slug and updated in place.

The photos are generated by store/mockimages.py. They are deliberately
illustrations rather than real product shots: a reseller photographs their
own stock, and copying a brand's catalogue imagery is not ours to do.
"""
from decimal import Decimal
from io import BytesIO

from django.core.files.base import ContentFile
from django.core.management.base import BaseCommand
from django.db import transaction
from django.utils.text import slugify

from store.mockimages import render
from store.models import Brand, Category, Product, ProductVariant

CATEGORIES = [
    ("Bags", "Totes, crossbodies and evening bags.", 1),
    ("Shoes", "Heels and trainers, EU sizing.", 2),
    ("Jewellery", "Everyday pieces in silver and gold tone.", 3),
    ("Gold", "Hallmarked gold, sold by karat and weight.", 4),
    ("Watches & Tech", "Smart watches and audio.", 5),
]

# (name, kind, country, sort order)
BRANDS = [
    ("Chanel", "fashion", "France", 1),
    ("Dior", "fashion", "France", 2),
    ("Kate Spade", "fashion", "United States", 3),
    ("Steve Madden", "fashion", "United States", 4),
    ("Guess", "fashion", "United States", 5),
    ("Aldo", "fashion", "Canada", 6),
    ("Charles & Keith", "fashion", "Singapore", 7),
    ("Lacoste", "fashion", "France", 8),
    ("Apple", "fashion", "United States", 9),
    ("Bindel", "fashion", "Malaysia", 10),
    ("Habib Jewels", "gold", "Malaysia", 1),
    ("Hani Gold", "gold", "Malaysia", 2),
    ("Malabar Gold & Diamonds", "gold", "India", 3),
]

# 24K reads deeper and more orange than 22K; 21K is paler. Using the real
# tonal differences also stops two gold items rendering identically.
GOLD_22K = "#d4af37"
GOLD_21K = "#cfa95c"
GOLD_24K = "#e8b320"

PRODUCTS = [
    # ---- Bags ----------------------------------------------------------
    {
        "name": "Madison Saffiano Tote",
        "brand": "Kate Spade", "category": "Bags",
        "price": "18500", "sale_price": "15900",
        "shape": "handbag", "colour": "#b03a5b", "finish": "leather",
        "sizes": {"OS": 4}, "featured": True,
        "description": (
            "Crosshatched saffiano leather that resists scuffing, with a "
            "gold-tone clasp and a fully lined interior.\n\n"
            "Fits an A4 folder and a 13-inch laptop."
        ),
    },
    {
        "name": "Classic Flap Bag, Small",
        "brand": "Chanel", "category": "Bags",
        "price": "685000", "sale_price": None,
        "shape": "flap_bag", "colour": "#1c1c1e", "finish": "leather",
        "sizes": {"OS": 1}, "featured": True,
        "description": (
            "Diamond-quilted lambskin with the interlocking turn-lock and a "
            "chain-and-leather shoulder strap.\n\n"
            "One piece only. Comes with dust bag and authenticity card."
        ),
    },
    {
        "name": "Quilted Chain Shoulder Bag",
        "brand": "Charles & Keith", "category": "Bags",
        "price": "7900", "sale_price": "6500",
        "shape": "flap_bag", "colour": "#d8c3c8", "finish": "leather",
        "sizes": {"OS": 6}, "featured": False,
        "description": (
            "Quilted faux leather with a detachable chain strap. Wear it "
            "cross-body or doubled up on the shoulder."
        ),
    },
    {
        "name": "Noelle Logo Crossbody",
        "brand": "Guess", "category": "Bags",
        "price": "9800", "sale_price": None,
        "shape": "flap_bag", "colour": "#c08a5e", "finish": "leather",
        "sizes": {"OS": 5}, "featured": False,
        "description": (
            "Compact crossbody in logo-embossed faux leather, with an "
            "adjustable strap and a card slip inside."
        ),
    },
    {
        "name": "Saddle Bag, Grained Calfskin",
        "brand": "Dior", "category": "Bags",
        "price": "520000", "sale_price": None,
        "shape": "flap_bag", "colour": "#1b2a4a", "finish": "leather",
        "sizes": {"OS": 1}, "featured": False,
        "description": (
            "The curved saddle silhouette in grained calfskin, with an "
            "antique-finish metal clasp.\n\nOne piece only."
        ),
    },
    {
        "name": "Everyday Leather Tote",
        "brand": "Bindel", "category": "Bags",
        "price": "6900", "sale_price": None,
        "shape": "handbag", "colour": "#6b4a33", "finish": "leather",
        "sizes": {"OS": 8}, "featured": False,
        "description": (
            "Full-grain cowhide that darkens with use. Unlined, with a single "
            "slip pocket — built to be carried daily rather than kept."
        ),
    },
    # ---- Shoes ---------------------------------------------------------
    {
        "name": "Klaire Pointed Pump",
        "brand": "Steve Madden", "category": "Shoes",
        "price": "11500", "sale_price": "9900",
        "shape": "heel", "colour": "#1c1c1e", "finish": "leather",
        "sizes": {"36": 3, "37": 5, "38": 6, "39": 4, "40": 2}, "featured": True,
        "description": (
            "A 90mm stiletto with a pointed toe and a lightly padded "
            "footbed.\n\nTrue to size. EU sizing."
        ),
    },
    {
        "name": "Stessy Court Shoe",
        "brand": "Aldo", "category": "Shoes",
        "price": "9900", "sale_price": None,
        "shape": "heel", "colour": "#8a1f36", "finish": "leather",
        "sizes": {"36": 2, "37": 4, "38": 5, "39": 3, "40": 1}, "featured": False,
        "description": "Classic pointed court shoe on a slim 85mm heel.",
    },
    {
        "name": "Patent Slingback Heel",
        "brand": "Charles & Keith", "category": "Shoes",
        "price": "8500", "sale_price": None,
        "shape": "heel", "colour": "#d8c3c8", "finish": "leather",
        # 36 deliberately empty so the sold-out styling is visible.
        "sizes": {"36": 0, "37": 4, "38": 6, "39": 3}, "featured": False,
        "description": (
            "Patent finish with an elasticated slingback strap that stays put "
            "without digging in."
        ),
    },
    {
        "name": "Carnaby Leather Trainer",
        "brand": "Lacoste", "category": "Shoes",
        "price": "12900", "sale_price": None,
        "shape": "sneaker", "colour": "#f2f1ec", "finish": "leather",
        "sizes": {"37": 2, "38": 4, "39": 5, "40": 5, "41": 3, "42": 2},
        "featured": False,
        "description": (
            "Leather upper on a vulcanised rubber cup sole, with the "
            "embroidered crocodile at the heel."
        ),
    },
    {
        "name": "Possession Chunky Trainer",
        "brand": "Steve Madden", "category": "Shoes",
        "price": "13500", "sale_price": "11900",
        "shape": "sneaker", "colour": "#2e3a4f", "finish": "leather",
        "sizes": {"37": 3, "38": 4, "39": 4, "40": 3, "41": 2}, "featured": False,
        "description": "Chunky platform trainer with a mixed-material upper.",
    },
    # ---- Jewellery -----------------------------------------------------
    {
        "name": "Crystal Drop Earrings",
        "brand": "Guess", "category": "Jewellery",
        "price": "4200", "sale_price": None,
        "shape": "earrings", "colour": "#c9ccd1", "finish": "metal",
        "sizes": {"OS": 7}, "featured": False,
        "description": "Rhodium-plated studs with a faceted crystal drop.",
    },
    {
        "name": "Pavé Pendant Necklace",
        "brand": "Kate Spade", "category": "Jewellery",
        "price": "6800", "sale_price": "5600",
        "shape": "necklace", "colour": "#c9ccd1", "finish": "metal",
        "sizes": {"OS": 5}, "featured": False,
        "description": (
            "A pavé-set pendant on a 42cm chain with a 5cm extender."
        ),
    },
    {
        "name": "Logo Statement Ring",
        "brand": "Dior", "category": "Jewellery",
        "price": "38000", "sale_price": None,
        "shape": "ring", "colour": "#d9b65c", "finish": "metal",
        "sizes": {"OS": 2}, "featured": False,
        "description": "Gold-finish metal ring with an engraved logo band.",
    },
    {
        "name": "Hoop Drop Earrings",
        "brand": "Charles & Keith", "category": "Jewellery",
        "price": "3400", "sale_price": None,
        "shape": "earrings", "colour": "#d9b65c", "finish": "metal",
        "sizes": {"OS": 9}, "featured": False,
        "description": "Lightweight gold-tone hoops, 35mm drop.",
    },
    # ---- Gold ----------------------------------------------------------
    {
        "name": "22K Gold Bangle, 12g",
        "brand": "Habib Jewels", "category": "Gold",
        "price": "165000", "sale_price": None,
        "shape": "bangle", "colour": GOLD_22K, "finish": "metal",
        "sizes": {"OS": 2}, "featured": True,
        "karat": "22K", "weight_grams": "12.00",
        "description": (
            "Hallmarked 22K bangle with a hand-finished edge. Sold with the "
            "jeweller's certificate and original receipt."
        ),
    },
    {
        "name": "21K Rope Chain Necklace, 18g",
        "brand": "Hani Gold", "category": "Gold",
        "price": "238000", "sale_price": None,
        "shape": "chain", "colour": GOLD_21K, "finish": "metal",
        "sizes": {"OS": 1}, "featured": False,
        "karat": "21K", "weight_grams": "18.00",
        "description": "A 55cm rope chain in 21K gold, with a lobster clasp.",
    },
    {
        "name": "22K Diamond-Cut Ring, 4.5g",
        "brand": "Malabar Gold & Diamonds", "category": "Gold",
        "price": "62000", "sale_price": None,
        "shape": "ring", "colour": GOLD_22K, "finish": "metal",
        "sizes": {"OS": 3}, "featured": False,
        "karat": "22K", "weight_grams": "4.50",
        "description": "Diamond-cut band that catches the light from every angle.",
    },
    {
        "name": "24K Gold Pendant, 6g",
        "brand": "Habib Jewels", "category": "Gold",
        "price": "92000", "sale_price": None,
        "shape": "necklace", "colour": GOLD_24K, "finish": "metal",
        "sizes": {"OS": 2}, "featured": False,
        "karat": "24K", "weight_grams": "6.00",
        "description": "Pure 24K pendant. Chain sold separately.",
    },
    {
        "name": "22K Bangle Pair, 20g",
        "brand": "Malabar Gold & Diamonds", "category": "Gold",
        "price": "275000", "sale_price": None,
        "shape": "bangle_pair", "colour": GOLD_22K, "finish": "metal",
        "sizes": {"OS": 1}, "featured": False,
        "karat": "22K", "weight_grams": "20.00",
        "description": "A matched pair of 22K bangles, 10g each.",
    },
    # ---- Watches & Tech ------------------------------------------------
    {
        "name": "Watch Series 9, 41mm GPS",
        "brand": "Apple", "category": "Watches & Tech",
        "price": "52900", "sale_price": None,
        "shape": "watch", "colour": "#1c1c1e", "finish": "metal",
        "sizes": {"OS": 4}, "featured": True,
        "description": (
            "Aluminium case with a sport band. Sealed box, Malaysian set, "
            "international warranty."
        ),
    },
    {
        "name": "AirPods Pro, 2nd generation",
        "brand": "Apple", "category": "Watches & Tech",
        "price": "28500", "sale_price": "26900",
        "shape": "earbuds", "colour": "#ffffff", "finish": "leather",
        "sizes": {"OS": 6}, "featured": False,
        "description": "Active noise cancellation with the USB-C charging case.",
    },
    {
        "name": "Watch SE, 40mm GPS",
        "brand": "Apple", "category": "Watches & Tech",
        "price": "34900", "sale_price": None,
        "shape": "watch", "colour": "#d9d9dd", "finish": "metal",
        "sizes": {"OS": 3}, "featured": False,
        "description": "The essentials of Apple Watch at a lower price.",
    },
]


class Command(BaseCommand):
    help = "Create mock categories, brands, products, sizes and stock."

    def add_arguments(self, parser):
        parser.add_argument(
            "--flush",
            action="store_true",
            help="Delete existing products, brands and orders first.",
        )
        parser.add_argument(
            "--images",
            action="store_true",
            help="Draw a product photo for each item (needs Pillow).",
        )

    @transaction.atomic
    def handle(self, *args, **options):
        if options["flush"]:
            self._flush()

        categories = {}
        for name, description, order in CATEGORIES:
            category, created = Category.objects.update_or_create(
                slug=slugify(name),
                defaults={
                    "name": name,
                    "description": description,
                    "sort_order": order,
                    "is_active": True,
                },
            )
            categories[name] = category
            self.stdout.write(f"  {'+' if created else '~'} section {name}")

        brands = {}
        for name, kind, country, order in BRANDS:
            brand, created = Brand.objects.update_or_create(
                slug=slugify(name),
                defaults={
                    "name": name,
                    "kind": kind,
                    "country": country,
                    "sort_order": order,
                    "is_active": True,
                },
            )
            brands[name] = brand
            self.stdout.write(f"  {'+' if created else '~'} brand {name}")

        for index, spec in enumerate(PRODUCTS):
            product, created = Product.objects.update_or_create(
                slug=slugify(f"{spec['brand']} {spec['name']}")[:220],
                defaults={
                    "name": spec["name"],
                    "brand": brands[spec["brand"]],
                    "category": categories[spec["category"]],
                    "description": spec["description"],
                    "price": Decimal(spec["price"]),
                    "sale_price": (
                        Decimal(spec["sale_price"]) if spec["sale_price"] else None
                    ),
                    "karat": spec.get("karat", ""),
                    "weight_grams": (
                        Decimal(spec["weight_grams"])
                        if spec.get("weight_grams")
                        else None
                    ),
                    "is_active": True,
                    "is_featured": spec["featured"],
                },
            )

            for size, stock in spec["sizes"].items():
                ProductVariant.objects.update_or_create(
                    product=product, size=size, defaults={"stock": stock}
                )

            if options["images"]:
                self._attach_image(product, spec, index)

            self.stdout.write(
                f"  {'+' if created else '~'} {spec['brand']} — {spec['name']} "
                f"({sum(spec['sizes'].values())} units)"
            )

        self.stdout.write(
            self.style.SUCCESS(
                f"\nDone. {Category.objects.count()} sections, "
                f"{Brand.objects.count()} brands, "
                f"{Product.objects.count()} products, "
                f"{ProductVariant.objects.count()} size rows."
                + ("" if options["images"] else "\nRe-run with --images for photos.")
                + "\nCreate a login with:  python manage.py createsuperuser"
            )
        )

    def _flush(self):
        from orders.models import Order

        Order.objects.all().delete()
        for product in Product.objects.exclude(image=""):
            product.image.delete(save=False)
        ProductVariant.objects.all().delete()
        Product.objects.all().delete()
        Brand.objects.all().delete()
        Category.objects.all().delete()
        self.stdout.write(self.style.WARNING("  flushed existing shop data"))

    def _attach_image(self, product, spec, seed):
        """Draw and attach a mock photo, replacing any previous one."""
        image = render(
            spec["shape"], spec["colour"], finish=spec["finish"], seed=seed
        )
        if product.image:
            product.image.delete(save=False)

        buffer = BytesIO()
        image.save(buffer, format="JPEG", quality=88, optimize=True)
        product.image.save(
            f"{product.slug}.jpg", ContentFile(buffer.getvalue()), save=True
        )
