# Generated by Django 4.2.30 on 2026-10-07 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.CharField(blank=True, max_length=250)),
                ('is_active', models.BooleanField(default=True, help_text='Untick to hide this category from the shop.')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first in the menu.')),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('description', models.TextField(blank=True, help_text='Fabric, fit, care instructions — shown on the product page.')),
                ('price', models.DecimalField(decimal_places=2, help_text='Regular price.', max_digits=10)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, help_text='Optional. Leave blank when the item is not discounted.', max_digits=10, null=True)),
                ('image', models.ImageField(blank=True, help_text='Square images look best. Uploaded straight to Cloudinary.', upload_to='products/')),
                ('is_active', models.BooleanField(default=True, help_text='Untick to take this product off the shop.')),
                ('is_featured', models.BooleanField(default=False, help_text='Featured products show on the home page first.')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='store.category')),
            ],
            options={
                'ordering': ['-is_featured', '-created'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('OS', 'One size')], max_length=4)),
                ('stock', models.PositiveIntegerField(default=0, help_text='Units on hand.')),
                ('sku', models.CharField(blank=True, help_text='Optional internal code.', max_length=60)),
                ('sort_order', models.PositiveSmallIntegerField(default=0, editable=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='store.product')),
            ],
            options={
                'ordering': ['sort_order', 'size'],
            },
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(fields=('product', 'size'), name='unique_size_per_product'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['slug'], name='store_produ_slug_361302_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-created'], name='store_produ_created_ca958a_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', 'is_featured'], name='store_produ_is_acti_23b747_idx'),
        ),
    ]
