# Generated by Django 4.2.30 on 2026-10-07 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('kind', models.CharField(choices=[('fashion', 'Fashion & lifestyle'), ('gold', 'Gold jeweller')], default='fashion', max_length=10)),
                ('country', models.CharField(blank=True, help_text='Where the label is from, e.g. France.', max_length=60)),
                ('description', models.CharField(blank=True, max_length=250)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='karat',
            field=models.CharField(blank=True, choices=[('18K', '18K'), ('21K', '21K'), ('22K', '22K'), ('24K', '24K')], help_text='Gold items only.', max_length=6),
        ),
        migrations.AddField(
            model_name='product',
            name='weight_grams',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Gold items only, in grams.', max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='size',
            field=models.CharField(choices=[('OS', 'One size'), ('35', 'EU 35'), ('36', 'EU 36'), ('37', 'EU 37'), ('38', 'EU 38'), ('39', 'EU 39'), ('40', 'EU 40'), ('41', 'EU 41'), ('42', 'EU 42')], max_length=4),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, help_text='Leave blank for unbranded stock.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='store.brand'),
        ),
    ]
