# Generated by Django 4.2.30 on 2026-10-07 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=120, verbose_name='full name')),
                ('phone', models.CharField(max_length=20, verbose_name='phone number')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(verbose_name='delivery address')),
                ('city', models.CharField(max_length=80)),
                ('area', models.CharField(choices=[('dhaka', 'Inside Dhaka'), ('outside', 'Outside Dhaka')], default='dhaka', help_text='Sets the delivery charge.', max_length=10)),
                ('note', models.TextField(blank=True, verbose_name='order note')),
                ('payment_method', models.CharField(choices=[('cod', 'Cash on Delivery'), ('bkash', 'bKash (manual transfer)'), ('nagad', 'Nagad (manual transfer)')], default='cod', max_length=10)),
                ('transaction_id', models.CharField(blank=True, help_text='The bKash/Nagad TrxID the customer submitted. Empty for COD.', max_length=60)),
                ('sender_number', models.CharField(blank=True, help_text='The wallet number the money came from.', max_length=20)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid (COD)'), ('awaiting', 'Awaiting verification'), ('verified', 'Verified'), ('rejected', 'Rejected / not found')], default='unpaid', max_length=10)),
                ('status', models.CharField(choices=[('new', 'New'), ('confirmed', 'Confirmed'), ('packed', 'Packed'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='new', max_length=12)),
                ('delivery_charge', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('size', models.CharField(blank=True, max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='store.productvariant')),
            ],
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['-created'], name='orders_orde_created_743fca_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='orders_orde_status_c6dd84_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_number'], name='orders_orde_order_n_f3ada5_idx'),
        ),
    ]
